### ISSUE TITLE
About

### ISSUE THREAD

**Issue by 1346075873** [YuyanWangSixTwo/EPLSIM#1]
Dear Wang，
      Sorry to bother you in this way, I read your published article—A family of partial-linear single-index models for analyzing complex environmental exposures with continuous, categorical, time-to-event, and longitudinal health outcomes. Thanks for releasing the data and code of this article.  I tried to run the code, and the running process was very smooth. But I have a question about this code. I found that in the code of PLSI model, there is no code about variable confidence interval. I have tried many methods but have not found a solution. Can you help me solve this problem? I will be very grateful. This question is very important to me.
      I am looking forward to your early reply.

                                                                                                                                                                                  yours sincerely,
                                                                                                                                                                                      Yuan miao

**Comment by YuyanWangSixTwo** [comment]
> 

Dear Miao,
Thanks for reaching out. When we published the EH paper, we applied a 'gam' wrapper and used bootstrapping to calculate the confidence intervals. For code in this package 'EPLSIM', we now implement the profiling method and write the code to calculate the CIs based on the asymptotic properties of the estimators. It supposes to work in this package. Let me try to figure out the bug and will let you know once it's working. Best. Yuyan

**Comment by 1346075873** [comment]
Dear Yuyan，
   Thanks for your reply, sorry to bother you once again. I would like to reconfirm that using the ‘gam’ package and the bootstrap is used to calculate the CIs of the link function in the EH paper? How calculated the CIs for exposure and covariates in the EH paper?
    I will continue to follow your account and look forward to your new content.
                                                                                                                                                                    yours sincerely,
                                                                                                                                                                       Yuan miao

**Comment by YuyanWangSixTwo** [comment]
> Dear Miao,

Sorry for the late response. Yes, in the EH paper, the single index function was calculated using a wrapper of the 'gam' function from 'mgcv' package and bootstrapping was used to calculate the confidence intervals. But in this package, we didn't use the 'gam' wrapper and changed the profile algorithm. Please find the details in the updated R code and feel free to reach out if you have further questions.

Thanks,
Yuyan
